# Generated by Django 5.2.4 on 2025-08-06 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='marketplace_name_c7bd47_idx'), models.Index(fields=['price'], name='marketplace_price_34d50e_idx'), models.Index(fields=['created_at'], name='marketplace_created_1f132e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_greater_than_or_equal_to_zero'), models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_greater_than_or_equal_to_zero')],
            },
        ),
    ]
