# Generated by Django 5.2.4 on 2025-08-10 16:11

from django.db import migrations


def assign_sellers(apps, schema_editor):
    Product = apps.get_model("marketplace", "Product")
    User = apps.get_model("auth", "User")

    # Get user of choice
    admin_user = User.objects.filter(is_superuser=True).first()
    if not admin_user:
        admin_user = User.objects.first()

    Product.objects.filter(seller__isnull=True).update(seller=admin_user)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_seller'),
    ]

    operations = [
        migrations.RunPython(assign_sellers, reverse_code=migrations.RunPython.noop),
    ]

