# Generated by Django 5.2.4 on 2025-08-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('books', 'Books & Stationery'), ('electronics', 'Electronics'), ('kitchen', 'Kitchenware'), ('furniture', 'Furniture'), ('clothing', 'Clothing')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='used', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_student_discount',
            field=models.BooleanField(default=False, help_text='Flag if special student pricing applies'),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_location',
            field=models.CharField(blank=True, default='On-campus', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period_months',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
