# Generated by Django 5.2.4 on 2025-08-24 22:58

from django.db import migrations
def populate_product_fields(apps,schema_editor):
    Product = apps.get_model("marketplace", "product")
    for p in Product.objects.all():
        if p.name is None:
            p.name = "Unnamed Product"
        if p.category is None:
            p.category = "None"
        if p.description is None:
            p.description = "No description provided."
        if p.condition is None:
            p.condition = "Not mentioned"
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_product_category_product_condition_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_product_fields, reverse_code=migrations.RunPython.noop),
    ]
