# Generated by Django 5.2.4 on 2025-07-27 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_desc', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2025, 7, 27, 19, 38, 49, 440334, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
