# Generated by Django 5.2.4 on 2025-07-27 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 27, 20, 5, 2, 179131, tzinfo=datetime.timezone.utc)),
        ),
    ]
