# Generated by Django 5.2.4 on 2025-07-29 03:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_alter_house_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='house_images/'),
        ),
        migrations.AddField(
            model_name='house',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='house_videos/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
