# Generated by Django 5.2.4 on 2025-07-30 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_house_image_house_video_alter_house_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='housing.house')),
            ],
        ),
    ]
