# Generated by Django 5.2.4 on 2025-08-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_housereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housereview',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
