# Generated by Django 5.2.4 on 2025-08-10 16:10

from django.db import migrations


def assign_owners(apps, schema_editor):
    House = apps.get_model("housing", "House")
    User = apps.get_model("auth", "User")

    # get the first super user or a specific user
    admin_user = User.objects.filter(is_superuser=True).first()
    if not admin_user:
        admin_user = User.objects.first()

    # update all houses to be owned by this user
    House.objects.filter(owner__isnull=True).update(owner=admin_user)


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_house_owner_housereview_author'),
    ]

    operations = [
        migrations.RunPython(assign_owners, reverse_code=migrations.RunPython.noop),
    ]
