# Generated by Django 5.2.4 on 2025-08-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0010_alter_favorite_house_alter_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
