# Generated by Django 5.2.4 on 2025-08-24 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0012_alter_house_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='available_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='house',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='house',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='house',
            name='lease_duration_months',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='house',
            name='max_occupants',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='house',
            name='num_bathrooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='num_bedrooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='proximity_to_campus',
            field=models.FloatField(default=1.0, help_text='Distance to campus in kilometers'),
        ),
        migrations.AddField(
            model_name='house',
            name='security_features',
            field=models.JSONField(default=dict, help_text="e.g. {'gated': True, 'guards': True, 'cctv': False}"),
        ),
        migrations.AddField(
            model_name='house',
            name='utilities_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
