# Generated by Django 5.2.4 on 2025-08-24 22:48

from django.db import migrations
from django.db import migrations

def populate_house_fields(apps, schema_editor):
    House = apps.get_model("housing", "House")
    for h in House.objects.all():
        # Fallback if still null
        if h.address is None:
            h.address = "Bambili University Area"
        if h.num_bedrooms is None:
            h.num_bedrooms = 1
        if h.furnished is None:
            h.furnished = False
        if h.has_wifi is None:
            h.has_wifi = False
        if h.location is None:
            h.location = "Bambili"
        if h.num_bathrooms is None:
            h.num_bathrooms = 1
        h.save()



class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0013_house_address_house_available_from_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_house_fields, reverse_code=migrations.RunPython.noop),
    ]
