# Generated by Django 5.2.4 on 2025-08-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0014_populate_new_house_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='video',
            field=models.FileField(upload_to='house_videos/'),
        ),
    ]
